name: "Github Release"

on:
  push:
    tags:
      - "*"

jobs:
  tagged-release:
    name: "Github Release"
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            artifact_name: jre-*-windows.zip
          - os: ubuntu-latest
            artifact_name: jre-*.tar.gz
          - os: macos-latest
            artifact_name: jre-*.tar.gz
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests=true -P ${{ matrix.os }} # Add the -P option here
    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: ${{ matrix.artifact_name }} # Use matrix variable here
